config.code=180426
config.username=fabrizio
config.message=hola como vá, mi ritmo. hola cómo está!, mulata
config.listOfValues=veintinueve,marzo,veintiseis
config.valuesMap={"product": "CPU Intel Core I3 9100", "description": "Coffe lake, 4 core, 3,60GHz", "price": "120"}